{
 "title": "GPU Drilldown",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(slurm_group_info{job=\"slurmctl_exporter\"}, node)"
    }
   },
   {
    "name": "GPU",
    "query": {
     "query": "label_values(gpu_utilization_percent{instance=~\".*$Node.*\"}, gpu)"
    }
   },
   {
    "name": "gpu_model_info",
    "query": {
     "query": "label_values(gpu_model_info{instance=~\"$Node:.*\"}, model)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Model",
   "type": "text",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:64px;\">\n<strong>${gpu_model_info}</strong>\n</div>"
   }
  },
  {
   "title": "GPU Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_utilization_percent{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(gpu_memory_used_bytes{gpu=\"$GPU\", instance=~\"$Node:.*\"} /\r\n gpu_memory_total_bytes{gpu=\"$GPU\", instance=~\"$Node:.*\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature (°C)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_temperature_c{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Draw (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_power_draw_percent{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_utilization_percent{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "GPU Utilization (%) on {{gpu}}"
    }
   ]
  },
  {
   "title": "Memory Utilization (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(gpu_memory_used_bytes{gpu=\"$GPU\", instance=~\"$Node:.*\"} / gpu_memory_total_bytes{gpu=\"$GPU\", instance=~\"$Node:.*\"}) * 100",
     "legendFormat": "Memory Utilization (%) on ${Node}"
    }
   ]
  },
  {
   "title": "GPU Temperature (°C)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "gpu_temperature_c{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "GPU Temperature (°C) on {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Draw (W)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "gpu_power_draw_watts{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "GPU Power Draw (W) on {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Process Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "gpu_process_count_by_gpu{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "GPU Process Count on {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Draw (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "gpu_power_draw_percent{gpu=\"$GPU\", instance=~\"$Node:.*\"}",
     "legendFormat": "GPU Power Draw (%) on {{gpu}}"
    }
   ]
  }
 ]
}