{
 "title": "Hello Grafana",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hpc_node",
    "query": {
     "query": "label_values(up{job=\"prometheus_exporter\"}, instance)"
    }
   },
   {
    "name": "instance",
    "label": "Server",
    "query": {
     "query": "label_values(gpu_temperature_c, instance)"
    }
   },
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(gpu_temperature_c{instance=\"$instance\"}, gpu)"
    }
   },
   {
    "name": "node_hostname",
    "query": {
     "query": "label_values(server_identity,hostname)"
    }
   },
   { "name": "Node", "label": "Node", "query": "ece-ugproj1,ece-ugproj2" }
  ]
 },
 "panels": [
  {
   "title": "${instance} — ${gpu}",
   "type": "gauge",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "repeat": "gpu",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_temperature_c{instance=\"$instance\", gpu=\"$gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "repeat": "gpu",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_temperature_c{instance=\"$instance\", gpu=\"$gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "${gpu}",
   "type": "gauge",
   "gridPos": { "h": 0, "w": 24, "x": 0, "y": 0 },
   "repeat": "gpu",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_temperature_c{instance=~\"$instance\", gpu=~\"$gpu\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Server: $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"text-align:center; font-size:64px; font-weight:700; padding:20px 0;\">\n    ${Node}\n</div>\n"
   }
  },
  {
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "repeat": "gpu",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gpu_temperature_c{instance=\"$Node:9401\"}",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "gpu_memory_per_user",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "gpu_memory_used_mem{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "gpu_sm_util_percent{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 39 },
   "targets": [
    {
     "expr": "gpu_process_count{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "ram_usage_mb{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 49 },
   "targets": [
    {
     "expr": "cpu_process_count{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}