{
 "title": "Server_level_graphs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "Group",
    "query": {
     "query": "label_values(slurm_group_node_count, group)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(slurm_group_info{group=~\"$Group\"}, node)"
    }
   },
   {
    "name": "gpu_model",
    "label": "gpu_model",
    "query": {
     "query": "label_values(gpu_model_info{instance=~\"$Node:9401\"}, model)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "server_cpu_count{job=\"prometheus_exporter\", instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\r\n  server_ram_total_bytes{job=\"prometheus_exporter\", instance=\"$Node:9401\"} / 1000^3,\r\n  0.01\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_max_power_draw_watts{job=\"prometheus_exporter\", instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_model_info{job=\"prometheus_exporter\", instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_custom_rx_max_bps{job=\"prometheus_exporter\", instance=\"$Node:9401\"} / 1e9",
     "legendFormat": "__auto"
    },
    {
     "expr": "cpu_model_info{job=\"prometheus_exporter\", instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\r\n  gpu_memory_total_bytes{job=\"prometheus_exporter\", instance=\"$Node:9401\"} / 1024^3,\r\n  0.1\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "round(\r\n  server_uptime_days{job=\"prometheus_exporter\", instance=\"$Node:9401\"},\r\n  0.01\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_process_total{job=\"prometheus_exporter\", instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\r\n  cpu_utilization_percent{instance=\"$Node:9401\"},\r\n  0.01\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "server_cpu_package_temperature_c{instance=\"$Node:9401\"}\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\r\n  server_ram_used_bytes{instance=\"$Node:9401\"} / server_ram_total_bytes{instance=\"$Node:9401\"} * 100,\r\n  0.01\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "round(\r\n  sum by (instance)(gpu_power_draw_watts{instance=\"$Node:9401\"}),\r\n  0.01\r\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (instance) (gpu_process_count_by_gpu{instance=\"$Node:9401\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Table",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "gpu_temperature_c{instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_power_draw_watts{instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_power_draw_percent{instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_process_count_by_gpu{instance=\"$Node:9401\"}\r\nor on(gpu) (max by (gpu) (gpu_model_info{instance=\"$Node:9401\"}) * 0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(gpu_memory_used_bytes{instance=\"$Node:9401\"} / gpu_memory_total_bytes{instance=\"$Node:9401\"}) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "gpu_utilization_percent{instance=\"$Node:9401\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RX (Download Speed)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_custom_rx_bytes_total{instance=~\"$Node:9401\"}[1m]) * 8",
     "legendFormat": "RX (Download Speed) on ${Node}"
    }
   ]
  },
  {
   "title": "TX (Upload Speed)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(node_custom_tx_bytes_total{instance=~\"$Node:9401\"}[1m]) * 8",
     "legendFormat": "TX (Upload Speed) on ${Node}"
    }
   ]
  }
 ]
}