{
 "title": "Usage and Util by User",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "hpc_node",
    "query": {
     "query": "label_values(up{job=\"prometheus_exporter\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gpu_sm_util_percent{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "gpu_process_count{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage (GB)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "ram_usage_mb{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Processes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "cpu_process_count{instance=~\"$hpc_node:.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}